### ISSUE TITLE
Upgrade zig-objc when it merges support for zig 0.14.0-dev

### ISSUE THREAD

**Issue by geon** [capy-ui/capy#98]
As of now, Capy can't build on macos because the required zig version (0.14.0-dev) broke compatibility with tagged union keys.

https://github.com/mitchellh/zig-objc/pull/9

**Comment by zenith391** [comment]
Ah I'm sorry, I didn't realise this as I don't have a Mac (although I had a VM but I need to update it) to test Capy on. If you'd like, I would love it if you updated `build.zig.zon` by linking to g-cassie's fork for the time being (and seeing if the macos backend still works). Otherwise, I'll use cross-compilation to spot compilation errors (but not runtime).

**Comment by geon** [comment]
I tried upgrading the dependency. That fixes the tagged union keys, but there are some other stuff that has broken as well, like the init function that inits monitors, which doesn't exist at all on macos. I'll have a look.
